rakesh/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import homepage
from .profiles.views import ProfileDetailView, ProfileEditView, ProfileListView


urlpatterns = patterns(
    "",
    url(r"^$", homepage, name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("kaleo.urls")),

    url(r"^profile/edit/", ProfileEditView.as_view(), name="profiles_edit"),
    url(r"^u/$", ProfileListView.as_view(), name="profiles_list"),

    url(r"^u/(?P<username>[\w\._-]+)/$", ProfileDetailView.as_view(), name="profiles_detail"),
    url(r"^t/", include("teams.urls")),

    url(r"", include("wiki.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rakesh/profiles/models.py
import os
import uuid

from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User


def avatar_upload(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join("avatars", filename)


class Profile(models.Model):

    user = models.ForeignKey(User)
    name = models.CharField(max_length=75, blank=True)
    avatar = models.ImageField(upload_to=avatar_upload, blank=True)
    bio = models.TextField(blank=True)
    affiliation = models.CharField(max_length=100, blank=True)
    location = models.CharField(max_length=100, blank=True)
    website = models.CharField(max_length=250, blank=True)
    twitter_username = models.CharField("Twitter Username", max_length=100, blank=True)

    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.modified_at = timezone.now()
        return super(Profile, self).save(*args, **kwargs)

    @property
    def display_name(self):
        if self.name:
            return self.name
        else:
            return self.user.username

rakesh/profiles/forms.py
import re

from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = [
            "name",
            "avatar",
            "bio",
            "affiliation",
            "location",
            "website",
            "twitter_username",
        ]

    def clean_twitter_username(self):
        value = self.cleaned_data["twitter_username"]
        value = value.strip()
        if not value:
            return value
        if value.startswith("@"):
            value = value[1:]
        m = re.match(r"^[a-zA-Z0-9_]{1,20}$", value)
        if not m:
            raise forms.ValidationError("invalid Twitter username")
        return value

rakesh/profiles/views.py
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, DetailView, ListView

from django.contrib import messages

from account.mixins import LoginRequiredMixin

from .forms import ProfileForm
from .models import Profile


class ProfileEditView(LoginRequiredMixin, UpdateView):

    form_class = ProfileForm
    model = Profile

    def get_object(self):
        return self.request.user.get_profile()

    def get_success_url(self):
        return reverse("profiles_list")

    def form_valid(self, form):
        response = super(ProfileEditView, self).form_valid(form)
        messages.success(self.request, "You successfully updated your profile.")
        return response


class ProfileDetailView(DetailView):

    model = Profile
    slug_url_kwarg = "username"
    slug_field = "user__username"
    context_object_name = "profile"


class ProfileListView(ListView):

    model = Profile
    context_object_name = "profiles"

rakesh/views.py
from django.shortcuts import render


def homepage(request):
    if request.user.is_authenticated():
        return render(request, "dashboard.html")
    else:
        return render(request, "homepage.html")

rakesh/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'profiles_detail' request.user.username %}"><i class="fa fa-user"></i> {% user_display request.user %}</a>
        </li>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

rakesh/templates/_latest_wikis.html
<div class="col-md-4">
    <h2>Latest Wiki Updates</h2>
    <ul>
        {% for revision in wiki.latest_edits %}
            <li><a href="{{ revision.page.get_absolute_url }}">{{ revision.page.slug }}</a> {{ revision.created_at }}</li>
        {% endfor %}
    </ul>
</div>
<div class="col-md-4">
    <h2>Table of Contents</h2>
    <ul>
        {% for page in wiki.pages.all %}
            <li><a href="{{ page.get_absolute_url }}">{{ page.slug }}</a></li>
        {% endfor %}
    </ul>
</div>

rakesh/templates/dashboard.html
{% extends "site_base.html" %}

{% load teams_tags %}

{% block head_title %}pinax-project-teams{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}

    {% if user.is_authenticated %}

        {% available_teams as available_teams %}
        {% if user.memberships.exists or available_teams %}
            <div class="dashboard-panel">
                <div class="dashboard-panel-header">
                    <i class="icon-group"></i>
                    <h3>Teams</h3>
                </div>

                <div class="dashboard-panel-content">
                    {% if user.memberships.exists %}
                        <h4>Your Teams</h4>
                        <table class="table table-striped">
                            {% for membership in user.memberships.all %}
                                <tr>
                                    <td>
                                        <a href="{% url 'team_detail' membership.team.slug %}">{{ membership.team.name }}</a>
                                        {% if membership.team.description %}<br>{{ membership.team.description }}{% endif %}
                                    </td>
                                    <td>
                                        <span class="label{% if membership.state == 'invited' %} label-info{% endif %}">{{ membership.get_state_display }}</span>
                                    </td>
                                    <td>
                                        {% if membership.state == "manager" or user.is_staff %}
                                            {% if membership.team.applicants %}{{ membership.team.applicants.count }} applicant{{ membership.team.applicants.count|pluralize }}{% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                    {% if available_teams %}
                        <h4>Available Teams</h4>
                        <table class="table table-striped">
                            {% for team in available_teams %}
                                <tr>
                                    <td>
                                        <a href="{% url 'team_detail' team.slug %}">{{ team }}</a>
                                        {% if team.description %}<br>{{ team.description }}{% endif %}
                                    </td>
                                    <td>
                                        <span class="label">{{ team.get_access_display }}</span>
                                    </td>
                                </tr>

                            {% endfor %}
                        </table>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

rakesh/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load teams_tags %}

{% block head_title %}rakesh{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>teams</h1>

   

    {% if ACCOUNT_OPEN_SIGNUP %}
        <div>
            <a class="btn btn-default" href="{% url 'account_signup' %}">{% trans "Sign up" %}</a>
            or
            <a class="btn btn-default" href="{% url 'account_login' %}">{% trans "Log in" %}</a>
        </div>
    {% endif %}

{% endblock %}

rakesh/templates/profiles/profile_detail.html
{% extends "site_base.html" %}

{% load wiki_tags %}

{% block head_title %}{{ profile.display_name }}{% endblock %}

{% load thumbnail %}

{% block body %}
    <div class="row">
        <div class="col-md-4">
            <div class="profile-widget">
                {% if profile.avatar %}
                    <img class="img-polaroid avatar hidden-phone" src="{% thumbnail profile.avatar 160x160 crop %}" alt="{{ profile.name }}">
                {% endif %}

                <h2>{{ profile.display_name }}</h2>

                <div class="profile">
                    {% if profile.bio %}
                        <div class="bio">
                            {{ profile.bio|linebreaks }}
                        </div>
                    {% endif %}
                    {% if profile.affiliation %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-institution"></i>
                            </span>
                            {{ profile.affiliation }}
                        </div>
                    {% endif %}
                    {% if profile.location %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-map-marker"></i>
                            </span>
                            {{ profile.location }}
                        </div>
                    {% endif %}
                    {% if profile.website %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-external-link"></i>
                            </span>
                            <a href="{{ profile.website }}">{{ profile.website }}</a>
                        </div>
                    {% endif %}
                    {% if profile.twitter_username %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-twitter"></i>
                            </span>
                            <a href="https://twitter.com/{{ profile.twitter_username }}/">@{{ profile.twitter_username }}</a>
                        </div>
                    {% endif %}
                    <div class="item">
                        <span class="dim">
                            <i class="fa fa-clock-o"></i>
                            Joined on
                        </span>
                        {{ profile.user.date_joined }}
                    </div>
                    {% if request.user == profile.user %}
                        <a href="{% url 'profiles_edit' %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> Edit Profile</a>
                    {% endif %}
                </div>
                <h4>Teams</h4>
                {% for membership in profile.user.memberships.all %}
                    <a href="{% url 'team_detail' membership.team.slug %}">{{ membership.team.name }}</a>
                    {% if not forloop.last %}&bull;{% endif %}
                {% empty %}
                    <p>None.</p>
                {% endfor %}
            </div>
        </div>
        {% wiki_for profile.user as wiki %}
        {% include "_latest_wikis.html" %}
    </div>
{% endblock %}

rakesh/templates/profiles/profile_form.html
{% extends "site_base.html" %}

{% load thumbnail %}
{% load url from future %}
{% load bootstrap %}

{% block body_class %}{{ block.super }} profile{% endblock %}

{% block head_title %}Edit Profile{% endblock %}

{% block extra_style %}
    <style type="text/css">
    .btn-avatar {
        position: relative;
        overflow: hidden;
    }
    .btn-avatar input {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        opacity: 0;
        filter: alpha(opacity=0);
        transform: translate(-300px, 0) scale(4);
        font-size: 23px;
        direction: ltr;
        cursor: pointer;
    }
    .remove input {
        float:left;
        margin-right: 10px;
    }
    </style>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-9">
            <form class="form profile-form" action="" method="POST" enctype="multipart/form-data">
                <legend>Edit Profile</legend>
                {% csrf_token %}
                {{ form.name|bootstrap }}
                <div id="div_id_avatar" class="control-group">
                    <label for="id_avatar" class="control-label">
                        Avatar
                    </label>
                    <div class="controls">
                        {% if profile.avatar %}
                            <img class="img-polaroid avatar hidden-phone" src="{% thumbnail profile.avatar 160x160 crop %}" alt="{{ profile.name }}" /><br />
                        {% endif %}
                        {% comment %}
                        <div class="preview-window" style="margin-top:20px;width:160px;height:160px;overflow:hidden;float:left;">
                            <img id="preview" style="max-width: none;" class="hide" src="" />
                        </div>
                        {% endcomment %}
                        {% comment %}
                        <div class="remove">
                            <label for="avatar-clear_id">Clear Avatar</label>
                            <input id="avatar-clear_id" name="avatar-clear" type="checkbox">
                        </div>
                        {% endcomment %}
                        <span class="btn btn-success btn-avatar btn-small">
                            <span>Select File</span>
                            <input id="id_avatar" name="avatar" type="file">
                        </span>
                        <span class="selected-filename"></span>
                    </div>
                </div>
                {{ form.bio|bootstrap }}
                {{ form.affiliation|bootstrap }}
                {{ form.location|bootstrap }}
                {{ form.website|bootstrap }}
                {% with field=form.twitter_username %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        {% if field.auto_id %}
                            <label class="control-label {{ classes.label }} {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label }}</label>
                        {% endif %}
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="{{ field.name }}" value="{{ field.value }}" class="form-control" />
                        </div>
                        {% for error in field.errors %}
                            <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                        {% endfor %}
                        {% if field.help_text %}
                            <p class="help-block">
                                {{ field.help_text|safe }}
                            </p>
                        {% endif %}
                    </div>
                {% endwith %}
                <button type="submit" class="btn btn-primary">Save</button>
                <a class="btn btn-default" href="{% url 'profiles_detail' request.user.username %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}


{% block extra_body %}
    {{ block.super }}
    <script type="text/javascript">
    $(function () {
        var loadImage = function(evt) {
            var input = evt.currentTarget;
            if (input.files && input.files[0]) {
                // var reader = new FileReader();
                // reader.onload = function(e) {
                //     $("#preview")
                //         .attr("src", "")
                //         .attr("style", "")
                //         .hide();
                //     $("#preview")
                //         .attr("src", e.target.result)
                //         .css({width: Math.round})
                //         .fadeIn();
                // }
                // reader.readAsDataURL(input.files[0]);
                $(".selected-filename").text(input.files[0].name);
            }
        }
        $("#id_avatar").change(loadImage);
    });
    </script>
{% endblock %}

rakesh/templates/profiles/profile_list.html
{% extends "site_base.html" %}

{% block head_title %}People{% endblock %}

{% load thumbnail %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1>People</h1>
        </div>
    </div>
    <div class="row">
        {% for profile in profiles %}
            <div class="col-md-3">
                <div class="media" style="margin-bottom: 16px;">
                    {% if profile.avatar %}
                        <img width="72" height="72" class="media-object pull-left" src="{% thumbnail profile.avatar 72x72 crop %}" alt="{{ profile.name|default:user.username }}">
                    {% else %}
                        <div class="default-avatar media-object pull-left">
                            <i class="fa fa-user fa-4x"></i>
                        </div>
                    {% endif %}

                    <div class="media-body">
                        <h4 class="media-heading"><a href="{% url 'profiles_detail' username=profile.user.username %}">{{ profile.display_name }}</a></h4>
                    {% if profile.affiliation %}
                        <div>
                            <span class="dim">
                                <i class="fa fa-institution"></i>
                            </span>
                            {{ profile.affiliation }}
                        </div>
                    {% endif %}
                    {% if profile.location %}
                        <div>
                            <span class="dim">
                                <i class="fa fa-map-marker"></i>
                            </span>
                            {{ profile.location }}
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

rakesh/templates/site_base.html
{% extends "theme_base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}


{% block style_base %}
    <link href="{% static "pinax/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    {% block extra_style %}{% endblock %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}

{% block nav %}
    <ul class="nav navbar-nav pull-left">
        <li><a href="{% url 'profiles_list' %}">People</a></li>
        <li><a href="{% url 'team_list' %}">Teams</a></li>
    </ul>
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}


{% block script_base %}
    <script src="{% block jquery_src %}{% static "pinax/js/jquery.js" %}{% endblock %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "pinax/js/theme.js" %}"></script>
    <script src="{% static "js/jquery.ui.widget.js" %}"></script>
    <script src="{% static "js/jquery.fileupload.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    {% block extra_script %}{% endblock %}
{% endblock %}

rakesh/templates/teams/_invite_form.html
{% load bootstrap %}
<form method="post" class="ajax invite-form" data-replace=".invite-form" action="{% url "team_invite" team.slug %}">
    {% csrf_token %}
    {{ invite_form|bootstrap }}
    <button class="btn btn-primary">Invite</button>
</form>

{% if request.is_ajax %}
<script>loadSelect2();</script>
{% endif %}

rakesh/templates/teams/_membership.html
<tr>
    <td class="btn-group">
    </td>
    <td>{{ membership.invitee }}</td>
    <td>{{ membership.role }}</td>
    <td>{{ membership.status }}</td>
    <td>{{ membership.created }}</td>
</tr>

rakesh/templates/teams/_team_actions.html
<div>
    {% if role == "owner" or role == "manager" %}
        <a class="btn btn-default btn-xs" href="{% url 'team_manage' team.slug %}">manage</a>
    {% endif %}
    {% if role == "owner" %}
        <a class="btn btn-default btn-xs" href="{% url 'team_edit' team.slug %}">edit</a>
    {% endif %}
</div>


{% if state == "invited" %}
    <p>
        You have been invited to join this team.
        Click <b>join</b> below to accept.
    </p>
{% endif %}

<div>
    {% if can_join %}
        <form method="post" action="{% url 'team_join' team.slug %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="join">
        </form>
    {% endif %}

    {% if can_leave %}
        <form method="post" action="{% url 'team_leave' team.slug %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-default" value="leave">
        </form>
    {% endif %}

    {% if can_apply %}
        <form method="post" action="{% url 'team_apply' team.slug %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="apply">
        </form>
    {% endif %}
</div>

rakesh/templates/teams/team_detail.html
{% extends "site_base.html" %}

{% load bootstrap %}
{% load thumbnail %}
{% load wiki_tags %}

{% block head_title %}{{ team.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-4">
            {% if team.avatar %}
                <img class="img-polaroid avatar hidden-phone" src="{% thumbnail team.avatar 160x160 crop %}" alt="{{ team.name }}">
            {% else %}
                <div class="default-avatar-big">
                    <i class="fa fa-group fa-5x"></i>
                </div>
            {% endif %}

            <h2>{{ team.name }}</h2>
            {% if role %}<p><span class="label label-default">{{ role }}</span></p>{% endif %}

            {% if team.description %}<p>{{ team.description }}</p>{% endif %}

            {% include "teams/_team_actions.html" %}

            <h4>Owners</h4>
            {% for membership in team.owners %}
                <a href="{% url 'profiles_detail' membership.user.username %}">{{ membership.user }}</a>
                {% if not forloop.last %}&bull;{% endif %}
            {% empty %}
                <p>None.</p>
            {% endfor %}

            <h4>Managers</h4>
            {% for membership in team.managers %}
                <a href="{% url 'profiles_detail' membership.user.username %}">{{ membership.user }}</a>
                {% if not forloop.last %}&bull;{% endif %}
            {% empty %}
                <p>None.</p>
            {% endfor %}

            <h4>Members</h4>
            {% for membership in team.members %}
                <a href="{% url 'profiles_detail' membership.user.username %}">{{ membership.user }}</a>
                {% if not forloop.last %}&bull;{% endif %}
            {% empty %}
                <p>None.</p>
            {% endfor %}

        </div>
        {% wiki_for team as wiki %}
        {% include "_latest_wikis.html" %}
    </div>
{% endblock %}

rakesh/templates/teams/team_form.html
{% extends "site_base.html" %}

{% load bootstrap %}
{% load thumbnail %}

{% block body_class %}teams{% endblock %}

{% block head_title %}Create Team{% endblock %}

{% block extra_style %}
    <style type="text/css">
    .btn-avatar {
        position: relative;
        overflow: hidden;
    }
    .btn-avatar input {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        opacity: 0;
        filter: alpha(opacity=0);
        transform: translate(-300px, 0) scale(4);
        font-size: 23px;
        direction: ltr;
        cursor: pointer;
    }
    .remove input {
        float:left;
        margin-right: 10px;
    }
    </style>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <form class="form profile-form" action="" method="POST" enctype="multipart/form-data">
                {% if team.pk %}
                    <legend>Edit Team</legend>
                {% else %}
                    <legend>Create Team</legend>
                {% endif %}

                {% csrf_token %}

                {{ form.name|bootstrap }}

                <div id="div_id_avatar" class="control-group">
                    <label for="id_avatar" class="control-label">
                        Avatar
                    </label>
                    <div class="controls">
                        {% if profile.avatar %}
                            <img class="img-polaroid avatar hidden-phone" src="{% thumbnail profile.avatar 160x160 crop %}" alt="{{ profile.name }}" /><br />
                        {% endif %}
                        <span class="btn btn-success btn-avatar btn-small">
                            <span>Select File</span>
                            <input id="id_avatar" name="avatar" type="file">
                        </span>
                        <span class="selected-filename"></span>
                    </div>
                </div>

                {{ form.description|bootstrap }}
                {{ form.member_access|bootstrap }}
                {{ form.manager_access|bootstrap }}

                <button type="submit" class="btn btn-primary">Save</button>
                {% if team.pk %}
                    <a class="btn btn-default" href="{% url 'team_detail' team.slug %}">Cancel</a>
                {% else %}
                    <a class="btn btn-default" href="{% url 'team_list' %}">Cancel</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

rakesh/templates/teams/team_list.html
{% extends "site_base.html" %}

{% block head_title %}Teams{% endblock %}

{% load thumbnail %}

{% block body %}
    <div class="row">
        <div class="col-md-12">

            <h1>Teams <a class="btn btn-default" href="{% url 'team_create' %}"><i class="fa fa-plus"></i> Create Team</a></h1>
        </div>
    </div>
    <div class="row">
        {% for team in teams %}
            <div class="col-md-3">
                <div class="media" style="margin-bottom: 16px;">
                    {% if team.avatar %}
                        <img width="72" height="72" class="media-object pull-left" src="{% thumbnail team.avatar 72x72 crop %}" alt="{{ profile.name|default:user.username }}">
                    {% else %}
                        <div class="default-avatar media-object pull-left">
                            <i class="fa fa-group fa-3x"></i>
                        </div>
                    {% endif %}

                    <div class="media-body">
                        <h4 class="media-heading"><a href="{% url 'team_detail' slug=team.slug %}">{{ team.name }}</a></h4>
                        {{ team.get_access_display }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

rakesh/templates/theme_bootstrap/subnav_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_base %}
    <section id="content_body">
        <div class="container">
            {% include "_messages.html" %}
            <div class="row">
                <div class="col-md-3 columns">
                    {% block subnav %}
                    {% endblock %}
                </div>
                <div class="col-md-9 columns">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

rakesh/templates/wiki/edit.html
{% extends "site_base.html" %}

{% load bootstrap %}

{% block title %}
    {% if page.pk %}
        Edit {{ page.slug }}
    {% else %}
        Add {{ page.slug }}
    {% endif %}
{% endblock %}

{% block body_class %}wiki-edit{% endblock %}

{% block body %}
    <h1>
        {% if page.pk %}
            Edit {{ page.slug }}
        {% else %}
            Add {{ page.slug }}
        {% endif %}
    </h1>

    <form class="form dropzone" method="POST" action="">
        {% csrf_token %}
        <p>
            To include an image on a card, drag it to this form or <a href="#" class="file-browse">browse for a file</a>.
        </p>
        <input type="file" class="hide fileupload" name="files" data-url="{% url 'wiki_file_upload' %}" multiple>
        <div class="progress progress-striped hide">
            <div class="progress-bar" role="progressbar" style="width: 0%;"></div>
        </div>
        {{ form|bootstrap }}
        <div class="pull-right">
            <a href="{{ page.get_absolute_url }}" class="btn btn-default">Cancel</a>
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

rakesh/templates/wiki/page.html
{% extends "site_base.html" %}

{% block body %}

    {% if can_edit %}
        <a class="pull-right btn btn-xs btn-primary" href="{{ revision.page.get_edit_url }}">Edit</a>
    {% endif %}

    <div class="page">
        {{ revision.content_html|safe }}
    </div>
{% endblock %}